### ISSUE TITLE
new profile fails

### ISSUE THREAD

**Issue by brettowe** [k4yt3x/wireguard-mesh-configurator#6]
trying to use this app and I'm not seeing results like screenshots indicate.

sudo pip3 install -r requirements.txt 
Requirement already satisfied: avalon_framework in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: readline in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (6.2.4.1)
Requirement already satisfied: netaddr in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.7.19)

python3 wireguard_mesh_configurator.py int
WireGuard Mesh Configurator 1.2.0
(C) 2018-2019 K4YT3X
Licensed under GNU GPL v3
[WGC]> new
[!] WARNING: This will flush the currently loaded profile!
[WGC]>

running arch linux
python3 --version
Python 3.8.1

**Comment by k4yt3x** [comment]
I don't see what failed exactly.

**Comment by brettowe** [comment]
is there a way to easily add a trace?

**Comment by k4yt3x** [comment]
> is there a way to easily add a trace?

There's not. Why do you think it failed?

**Comment by brettowe** [comment]
looking at screenshots posted in the readme and as per what I recall happening last time I used it I expect it to start asking for client stuff as soon as new is used, but its just returning to prompt.

**Comment by k4yt3x** [comment]
Ah I see. The screenshots are for version 1.1.x, where the newest master branch is on 1.2.x. You'll have to use `addpeer` command to enroll a new peer.

There are major changes coming in version 1.3.0 which is on another branch, and I have been planning to update documentations when 1.3 is out, which is why the documentation is slightly outdated. You can use help command or double tap <tab> to see all commands available. They should be pretty intuitive.
